version: '3.8'

networks:
  default:
    external:
      name: my-interservice-network

services:
  server:
    build: .
    ports:
    - "5000:5000"
    tty: true
    depends_on:
      - database
    environment:
      - DATABASE_HOSTNAME=database
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password1234

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password1234
  
  cache:
      image: redis:latest